"""The committed Phase 3E ablation artifacts (evals/baselines/ablation/): 10 runs × 3 ablations,
each an ablated simulated bundle plus its regression output, and summary.md/summary.json
regenerated byte for byte from the committed regression.json files. Offline."""

import json
from pathlib import Path

from relay.traces.models import RunManifest
from scripts.phase3e_table import collect, render

REPO = Path(__file__).resolve().parents[2]
ROOT = REPO / "evals" / "baselines" / "ablation"
ABLATIONS = {
    "contradiction": ["contradiction"],
    "missing_evidence": ["missing_evidence"],
    "contradiction+missing_evidence": ["contradiction", "missing_evidence"],
}
# (dataset, run directory name) -> (committed source run directory, auto_process used)
RUNS = {
    ("gen-v0.2-holdout", "jev-q-v0.2"): ("gen-v0.2-holdout/run_20260925T075242Z_fd455f", 0.89),
    ("gen-v0.2-holdout", "rules"): ("gen-v0.2-holdout/run_20260925T092425Z_0aee97", 0.99),
    ("gen-v0.2-holdout", "claude-150"): ("gen-v0.2-holdout/run_20260925T212034Z_bbee49", 0.55),
    ("gen-v0.3-holdout", "jev-q-v0.3"): ("gen-v0.3-holdout/run_20260927T072144Z_12e1e4", 0.81),
    ("gen-v0.3-shift", "jev-q-v0.3-aware"): ("gen-v0.3-shift/aware-immunara-v0.2", 0.95),
    ("gold-v0.1", "groundtruth"): ("gold-v0.1/run_20260925T170825Z_440df0", 0.95),
    ("gold-v0.1", "jev-q-v0.2"): ("gold-v0.1/run_20260925T170857Z_b95be9", 0.89),
    ("gold-v0.1", "rules"): ("gold-v0.1/run_20260925T170839Z_d3b427", 0.99),
    ("gold-v0.1", "claude"): ("gold-v0.1/run_20260926T011730Z_f1852f", 0.55),
    ("gold-v0.1", "jev-q-v0.3"): ("gold-v0.1/run_20260927T072623Z_ad6f44", 0.81),
}


def test_every_run_has_all_three_ablations_and_nothing_else():
    found = {tuple(p.relative_to(ROOT).parts[:3]) for p in ROOT.glob("*/*/*/regression.json")}
    assert found == {(d, r, a) for (d, r) in RUNS for a in ABLATIONS}


def test_each_bundle_records_its_source_ablation_and_operating_point():
    for (dataset, run), (source_dir, auto_process) in RUNS.items():
        source = json.loads(
            (REPO / "evals/baselines" / source_dir / "run-manifest.json").read_text()
        )
        for ablation, names in ABLATIONS.items():
            directory = ROOT / dataset / run / ablation
            raw = json.loads((directory / "run-manifest.json").read_text())
            manifest = RunManifest.model_validate(raw)
            label = f"{dataset}/{run}/{ablation}"
            assert (manifest.mode, manifest.ablation) == ("simulated", names), label
            assert manifest.source_run_id == source["run_id"], label
            assert raw["auto_process"] == auto_process, label
            assert manifest.sample_limit == source.get("sample_limit"), label
            assert (directory / "traces.jsonl.gz").is_file(), label
            assert (directory / "regression.md").is_file(), label


def test_the_summary_is_regenerated_from_the_committed_regression_files():
    rows = collect(ROOT)
    assert len(rows) == 30
    assert (ROOT / "summary.md").read_text(encoding="utf-8") == render(rows)
    assert json.loads((ROOT / "summary.json").read_text(encoding="utf-8")) == rows
