"""Phase 3E summary table over the committed ablation regression.json files (offline).

uv run python -m scripts.phase3e_table [ROOT]
    ROOT (default evals/baselines/ablation) holds <dataset>/<run>/<ablation>/regression.json,
    one per (run, ablation) pair: the run at its operating point (baseline) against the same
    stored decisions re-decided with the named gate(s) disabled (candidate). Writes
    ROOT/summary.md and ROOT/summary.json and prints the Markdown.
"""

import json
import sys
from pathlib import Path
from typing import Any

DEFAULT_ROOT = Path("evals/baselines/ablation")
DATASET_ORDER = ("gen-v0.2-holdout", "gen-v0.3-holdout", "gen-v0.3-shift", "gold-v0.1")
RUN_ORDER = (
    "groundtruth",
    "jev-q-v0.2",
    "rules",
    "claude",
    "claude-150",
    "jev-q-v0.3",
    "jev-q-v0.3-aware",
)
ABLATION_ORDER = ("contradiction", "missing_evidence", "contradiction+missing_evidence")

HEADER = [
    "# Gate ablation (Phase 3E)",
    "",
    "Generated by `uv run python -m scripts.phase3e_table` from the committed `regression.json`",
    "files beside it. Each row re-decides one committed run's stored decisions with the named",
    "engine gate(s) disabled (the candidate) and gates it against the same run at the same",
    "threshold (the baseline). Expected actions always come from the full engine. Offline, $0.",
    "",
    "| Dataset | Run | Provider | Thresholds | Ablation | Gate | Actions changed | Newly unsafe "
    "| Regressed | Improved | Automation (baseline → ablated) | UAR (baseline → ablated) |",
    "|---|---|---|---|---|---|---|---|---|---|---|---|",
]


def _rate(rate: dict[str, Any]) -> str:
    if rate["rate"] is None:
        return f"{rate['count']}/{rate['n']} (n/a)"
    ci = rate["ci95"]
    return f"{rate['count']}/{rate['n']} ({rate['rate']:.1%}) [{ci['low']:.1%}, {ci['high']:.1%}]"


def _order(values: tuple[str, ...], value: str) -> tuple[int, str]:
    return (values.index(value) if value in values else len(values), value)


def summary_row(dataset: str, run: str, ablation: str, result: dict[str, Any]) -> dict[str, Any]:
    """One table row from one regression.json (as a dict)."""
    base, cand = result["baseline"], result["candidate"]
    identity = cand["identity"]
    return {
        "dataset": dataset,
        "run": run,
        "source_run_id": base["identity"]["run_id"].removeprefix("replay-"),
        "provider": f"{identity['provider']} {', '.join(identity['question_set_versions'])}",
        "thresholds": ", ".join(identity["thresholds_versions"]),
        "ablation": ablation,
        "verdict": result["verdict"],
        "n": result["n"],
        "actions_changed": result["n"] - result["change_counts"]["unchanged"],
        "newly_unsafe": [entry["case_id"] for entry in result["newly_unsafe"]],
        "regressed": len(result["regressed"]),
        "improved": len(result["improved"]),
        "automation": {"baseline": base["automation"], "ablated": cand["automation"]},
        "uar": {"baseline": base["uar"], "ablated": cand["uar"]},
    }


def collect(root: Path) -> list[dict[str, Any]]:
    """Every <dataset>/<run>/<ablation>/regression.json under root, as rows in table order."""
    rows = [
        summary_row(
            path.parts[-4],
            path.parts[-3],
            path.parts[-2],
            json.loads(path.read_text(encoding="utf-8")),
        )
        for path in root.glob("*/*/*/regression.json")
    ]
    return sorted(
        rows,
        key=lambda r: (
            _order(DATASET_ORDER, r["dataset"]),
            _order(RUN_ORDER, r["run"]),
            _order(ABLATION_ORDER, r["ablation"]),
        ),
    )


def render(rows: list[dict[str, Any]]) -> str:
    lines = list(HEADER)
    for r in rows:
        unsafe = r["newly_unsafe"]
        unsafe_cell = f"{len(unsafe)} ({', '.join(unsafe)})" if unsafe else "0"
        lines.append(
            f"| {r['dataset']} | {r['run']} (`{r['source_run_id']}`) | {r['provider']} | "
            f"{r['thresholds']} | {r['ablation']} | {r['verdict']} | "
            f"{r['actions_changed']}/{r['n']} | {unsafe_cell} | {r['regressed']} | "
            f"{r['improved']} | {_rate(r['automation']['baseline'])} → "
            f"{_rate(r['automation']['ablated'])} | {_rate(r['uar']['baseline'])} → "
            f"{_rate(r['uar']['ablated'])} |"
        )
    null = [r for r in rows if r["actions_changed"] == 0]
    lines += ["", f"Null results (no action changed): {len(null)}"]
    lines += [f"- {r['dataset']} / {r['run']} × {r['ablation']}" for r in null] or ["- none"]
    failing = [r for r in rows if r["verdict"] == "FAIL"]
    lines += ["", f"Pairs whose gate FAILs (a newly unsafe automation): {len(failing)}"]
    lines += [
        f"- {r['dataset']} / {r['run']} × {r['ablation']}: {', '.join(r['newly_unsafe'])}"
        for r in failing
    ] or ["- none"]
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) > 1:
        print(__doc__, file=sys.stderr)
        return 2
    root = Path(argv[0]) if argv else DEFAULT_ROOT
    rows = collect(root)
    if not rows:
        print(f"no */*/*/regression.json under {root}", file=sys.stderr)
        return 2
    text = render(rows)
    (root / "summary.md").write_text(text, encoding="utf-8")
    (root / "summary.json").write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8")
    print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
